name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      env:
          GOPATH: /home/runner/projektowanie-echo-go
    - name: Build
      run: 
           go get github.com/mattn/go-sqlite3
           go build server.go
           go run server.go
